---

- name: Registering the platform domain
  shell: "grep platform_domain /opt/xayma-platform-defaults.yml | cut -d ':' -f2 | awk '{$1=$1};1'"
  register: _platform_domain
- set_fact:
    platform_domain: "{{ _platform_domain.stdout }}"


- name: Registering the portal domain
  shell: "grep portal_domain /opt/xayma-platform-defaults.yml | cut -d ':' -f2 | awk '{$1=$1};1'"
  register: _portal_domain
- set_fact:
    portal_domain: "{{ _portal_domain.stdout }}"

- name: Registering the orchestrator domain
  shell: "grep orchestrator_domain /opt/xayma-platform-defaults.yml | cut -d ':' -f2 | awk '{$1=$1};1'"
  register: _orchestrator_domain
- set_fact:
    orchestrator_domain: "{{ _orchestrator_domain.stdout }}"

- name: Registering the front network
  shell: "grep front_network /opt/xayma-platform-defaults.yml | cut -d ':' -f2 | awk '{$1=$1};1'"
  register: _front_network
- set_fact:
    front_network: "{{ _front_network.stdout }}"

- name: Registering the service path
  shell: "grep services_path /opt/xayma-platform-defaults.yml | cut -d ':' -f2 | awk '{$1=$1};1'"
  register: _services_path
- set_fact:
    services_path: "{{ _services_path.stdout }}"

- name: Registering the addons volume
  shell: "grep addons_volume /opt/xayma-platform-defaults.yml | cut -d ':' -f2 | awk '{$1=$1};1'"
  register: _addons_volume
- set_fact:
    addons_volume: "{{ _addons_volume.stdout }}"

- name: Registering the preferred reverse proxy
  shell: "grep preferred_reverse_proxy /opt/xayma-platform-defaults.yml | cut -d ':' -f2 | awk '{$1=$1};1'"
  register: _preferred_reverse_proxy
- set_fact:
    preferred_reverse_proxy: "{{ _preferred_reverse_proxy.stdout }}"
