---
- name: Stoping moodle instance
  docker_compose:
    project_src: "{{ xayma_moodleapp_paths.instance }}"
    state: absent
  when: instancename != xayma_moodleapp.instancename # We make sure the user has provided an instance name
